### ISSUE TITLE
Issues with AE2 autocrafting

### ISSUE THREAD

**Issue by JJSax** [jaredlll08/RecipeStages#19]
I had updated Modern skyblock 3 and from 3.4.1.2 to 3.4.1.4 and the items that had originally been locked were unable to be crafted through AE2, though I could manually craft them. Uninstalled this mod, and despite now having to wait a ridiculously long time for my world to load, I was able to craft everything.

**Comment by jaredlll08** [comment]
Doesn't sound like my issue, report to modpack maker.

**Comment by Valerate** [comment]
I dont think you should dismiss it that easily, there is more than one reddit thread with someone with this issue, and people seem to conclude its the stages mod (one of them) causing it.

https://www.reddit.com/r/feedthebeast/comments/8ve32h/me_crafting_terminal_not_crafting/
https://www.reddit.com/r/feedthebeast/comments/8wufdm/ae2_autocrafting_issues/

**Comment by jaredlll08** [comment]
Except they are also using modern Skyblock 4, which never updated recipe stages because I don't have any updates.

Therefor, what probably happened is that AE changed a package name or class name and now the code I have that ignores stage checking on crafter isn't working because the modern Skyblock dev needs to update their scripts. 

You can make 100 reddit threads, it isn't going to make this anymore my issue than it currently is (or rather isn't)

**Comment by kylev** [comment]
See EmosewaPixel/Modern-Skyblock-3#636.
