### ISSUE TITLE
Recipe Stages not recognizing containers

### ISSUE THREAD

**Issue by North-West-Wind** [jaredlll08/RecipeStages#48]
I have `mods.recipestages.Recipes.setPrintContainers(true);` in a file in the scripts folder.

When I craft staged recipes, I was expecting the container name to appear in crafttweaker.log.
However, some containers don't appear in the log. For example, Cyclic's Crafting Machine and RFTools' Crafter. But some do get logged into the file. For example, Cyclic's Crafting Stick.

I tried manually adding package names to the script (`com.simibubi.create` and `mcjty.rftoolsutility`) but the containers that aren't logged still cannot craft staged recipes.

**Comment by jaredlll08** [comment]
So I looked into the crafting machine from cyclic, that does fake crafting, there is nothing I can do about that.

I don't feel like going through rftools code to see what they do, but basically, if the container is not being printed, and there is nothing in the crafttweaker.log file about it, then that crafting system just doesn't support custom recipes like staged recipes and nothing you or I do can fix that.

You should probably report it to the other mod authors so they are aware, since this would also affect custom crafting recipes like ones that use experience.

**Comment by North-West-Wind** [comment]
Alright. Thanks for explaining that.
